export const HC = {
  bg: '#f4f0e8',
  paper: '#faf7f0',
  ink: '#1a1510',
  mute: '#6b6458',
  ruleFaint: 'rgba(26,21,16,0.12)',
  red: '#c4221b',
  redDim: '#a81a14',
  amber: '#d89430',
  green: '#2d6a3f',
  serif: '"Instrument Serif", "EB Garamond", Georgia, serif',
  sans: '"Inter", -apple-system, system-ui, sans-serif',
  mono: '"JetBrains Mono", ui-monospace, "SF Mono", Menlo, monospace',
} as const;

export const btn = {
  primary: {
    background: '#1a1510',
    color: '#faf7f0',
    border: 'none',
    fontFamily: '"JetBrains Mono", ui-monospace, Menlo, monospace',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.16em',
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
    padding: '12px 22px',
  },
  outline: {
    background: 'transparent',
    color: '#1a1510',
    border: '1px solid #1a1510',
    fontFamily: '"JetBrains Mono", ui-monospace, Menlo, monospace',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.16em',
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
    padding: '12px 22px',
  },
  danger: {
    background: '#c4221b',
    color: '#faf7f0',
    border: 'none',
    fontFamily: '"JetBrains Mono", ui-monospace, Menlo, monospace',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.18em',
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
    padding: '12px 22px',
  },
  amber: {
    background: '#d89430',
    color: '#1a1510',
    border: 'none',
    fontFamily: '"JetBrains Mono", ui-monospace, Menlo, monospace',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.16em',
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
    padding: '12px 22px',
  },
  ghost: {
    background: 'transparent',
    color: '#6b6458',
    border: 'none',
    fontFamily: '"JetBrains Mono", ui-monospace, Menlo, monospace',
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: '0.16em',
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
    padding: '12px 22px',
  },
} as const;
